### ISSUE TITLE
App won't start in Docker

### ISSUE THREAD

**Issue by magicalbanana** [tinode/chat#132]
### Subject of the issue
App won't stop in Docker

### Is this a bug report of a feature request?
- [x] Bug report
- [ ] Feature request

#### Server-side
- [ ] api.tinode.co
- [x] Your own setup:
  * Docker
  * RethinkDB

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
```
2018/07/31 04:48:28 Server 'v0.14:20180419T17:54:41Z:rethinkdb'; pid 33; started with 12 process(es)
2018/07/31 04:48:28 Using config from 'working.config'
2018/07/31 04:48:28 Running as a standalone server.
2018/07/31 04:48:28 plugins: no active plugins found
2018/07/31 04:48:28 Serving static content from 'static' at '/'
2018/07/31 04:48:28 Stopped push notifications
2018/07/31 04:48:28 Closed database connection(s)
2018/07/31 04:48:28 All done, good bye
panic: http: multiple registrations for /

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0xd9edc0, 0xa55465, 0x1, 0xacf480, 0xa7e888)
        /usr/local/go/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0xd9edc0, 0xa55465, 0x1, 0xa7e888)
        /usr/local/go/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0xa55465, 0x1, 0xa7e888)
        /usr/local/go/src/net/http/server.go:2380 +0x4b
main.main()
        /Users/gene/go/src/github.com/tinode/chat/server/main.go:341 +0x1410
bash-4.4#
```

**Comment by or-else** [comment]
It looks like you are using a build from April `v0.14:20180419T17:54:41Z:rethinkdb`. It does not support serving static content from `/`. Please use the `latest`.
