### ISSUE TITLE
GenDB issue

### ISSUE THREAD

**Issue by fstn** [tinode/chat#151]
At the startup:

```
`2018-09-11 15:36:02.000 CEST
panic: invalid argument to Intn goroutine 1 [running]: math/rand.(*Rand).Intn(0xc420064150, 0x0, 0xc4201c5c50) /usr/local/go/src/math/rand/rand.go:166 +0x9c math/rand.Intn(0x0, 0xc4201c5740) /usr/local/go/src/math/rand/rand.go:326 +0x37 main.genDb(0xc420047e01, 0xc42010e140, 0x123, 0xc4200fc000) /Users//IdeaProjects/chat/tinode-db/gendb.go:275 +0x3071 main.main() /Users//IdeaProjects/chat/tinode-db/makedb.go:180 +0x33c
Expand all | Collapse all {
 insertId:  "1xnbcvig1rkw329"  
 labels: {…}  
 logName:  "projects/wecom-205708/logs/wecom-backend-server"  
 receiveTimestamp:  "2018-09-11T13:36:40.702965014Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0xc420064150, 0x0, 0xc4201c5c50)
	/usr/local/go/src/math/rand/rand.go:166 +0x9c
math/rand.Intn(0x0, 0xc4201c5740)
	/usr/local/go/src/math/rand/rand.go:326 +0x37
main.genDb(0xc420047e01, 0xc42010e140, 0x123, 0xc4200fc000)
	/Users//IdeaProjects/chat/tinode-db/gendb.go:275 +0x3071
main.main()
	/Users//IdeaProjects/chat/tinode-db/makedb.go:180 +0x33c
"  
 timestamp:  "2018-09-11T13:36:02Z"  
}`
```

My data.json:
```
{
  "users": [
    {
      "createdAt": "-140h",
      "email": "support1@wemaik.com",
      "tel": "17025550001",
      "passhash": "A",
      "private": {
        "comment": "Support user1"
      },
      "public": {
        "fn": "Support 1",
        "photo": "alice-64.jpg",
        "type": "jpg"
      },
      "state": 1,
      "status": {
        "text": "DND"
      },
      "username": "support1",
      "addressBook": []
    },
    {
      "createdAt": "-138h",
      "email": "support2@wemaik.com",
      "tel": "17025550003",
      "passhash": "A",
      "private": {
        "comment": "Support user2"
      },
      "public": {
        "fn": "Support 2",
        "photo": "bob-64.jpg",
        "type": "jpg"
      },
      "state": 1,
      "status": "online",
      "username": "support2",
      "addressBook": []
    },
    {
      "createdAt": "-140h",
      "email": "francois@sncf.fr",
      "tel": "17025550004",
      "passhash": "A",
      "private": {
        "comment": "Client SNCF"
      },
      "public": {
        "fn": "Francois (SNCF)",
        "photo": "alice-64.jpg",
        "type": "jpg"
      },
      "state": 1,
      "status": {
        "text": "DND"
      },
      "username": "francois1",
      "addressBook": []
    },
    {
      "createdAt": "-138h",
      "email": "maryline@sncf.fr",
      "tel": "17025550005",
      "passhash": "A",
      "private": {
        "comment": "Client SNCF"
      },
      "public": {
        "fn": "Maryline (SNCF)",
        "photo": "bob-64.jpg",
        "type": "jpg"
      },
      "state": 1,
      "status": "online",
      "username": "maryline",
      "addressBook": []
    },
    {
      "createdAt": "-136h",
      "email": "paul@logitech.com",
      "tel": "17025550006",
      "passhash": "A",
      "private": {
        "comment": "Paul"
      },
      "public": {
        "fn": "Paul (logitech)",
        "photo": "carol-64.jpg",
        "type": "jpg"
      },
      "state": 1,
      "status": "online",
      "username": "paul",
      "addressBook": []
    }
  ],
  "grouptopics": [
    {
      "createdAt": "-128h",
      "name": "SNCF-Assistance",
      "owner": "support1",
      "tags": [
        "aide",
        "sncf"
      ],
      "public": {
        "fn": "SNCF-Assistance",
        "photo": "abc-64.jpg",
        "type": "jpg"
      }
    },
    {
      "createdAt": "-126h",
      "name": "SNCF-Contact",
      "owner": "support1",
      "tags": [
        "contact",
        "sncf"
      ],
      "public": {
        "fn": "SNCF-Contact",
        "photo": "abcdef-64.jpg",
        "type": "jpg"
      }
    },
    {
      "createdAt": "-128h",
      "name": "Logitech-Assistance",
      "owner": "support1",
      "tags": [
        "aide",
        "logitech"
      ],
      "public": {
        "fn": "Logitech-Assistance",
        "photo": "abc-64.jpg",
        "type": "jpg"
      }
    },
    {
      "createdAt": "-126h",
      "name": "Logitech-Contact",
      "owner": "support1",
      "tags": [
        "contact",
        "logitech"
      ],
      "public": {
        "fn": "Logitech-Contact",
        "photo": "abcdef-64.jpg",
        "type": "jpg"
      }
    }
  ],
  "p2psubs": [
    {
      "createdAt": "-119h",
      "users": [
        {
          "name": "support1"
        },
        {
          "name": "paul",
          "private": {
            "comment": "Support Paul"
          }
        }
      ]
    },
    {
      "createdAt": "-119h",
      "users": [
        {
          "name": "support1"
        },
        {
          "name": "maryline",
          "private": {
            "comment": "Support Maryline"
          }
        }
      ]
    },
    {
      "createdAt": "-119h",
      "users": [
        {
          "name": "support1"
        },
        {
          "name": "francois",
          "private": {
            "comment": "Support Francois"
          }
        }
      ]
    },
    {
      "createdAt": "-119h",
      "users": [
        {
          "name": "support2"
        },
        {
          "name": "paul",
          "private": {
            "comment": "Support Paul"
          }
        }
      ]
    },
    {
      "createdAt": "-149h",
      "users": [
        {
          "name": "support2"
        },
        {
          "name": "maryline",
          "private": {
            "comment": "Support Maryline"
          }
        }
      ]
    }
  ],
  "groupsubs": [
    {
      "createdAt": "-177h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "SNCF-Assistance",
      "user": "support1"
    },
    {
      "createdAt": "-166h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "Logitech-Assistance",
      "user": "support1"
    },
    {
      "createdAt": "-155h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "SNCF-Assistance",
      "user": "support2"
    },
    {
      "createdAt": "-145h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "Logitech-Assistance",
      "user": "support2"
    },
    {
      "createdAt": "-144h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "SNCF-Assistance",
      "user": "francois"
    },
    {
      "createdAt": "-133h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "SNCF-Assistance",
      "user": "maryline"
    },
    {
      "createdAt": "-110h",
      "private": {
        "comment": "Group topic"
      },
      "topic": "Logitech-Assistance",
      "user": "paul"
    }
  ],
  "messages": ["Merci"]
}

```

**Comment by or-else** [comment]
It seems to be due to the fact that you are inserting a single message. The code does not expect it. It should be an easy fix. Thanks for the report.

**Comment by fstn** [comment]
Thank you ;)
Stephen ZAMBAUX

0680114469

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/09/18
à 17:49:10
