### ISSUE TITLE
Some queries crash the server

### ISSUE THREAD

**Issue by afoninsky** [tinode/chat#255]
Example: `{ get topic='me' query: { what: 'sub desc' } }`

```
2019/07/05 10:22:48 grpc in: login:<id:"etqvye" scheme:"rest" secret:"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiJOZ0t5WS1YXzYiLCJyb2xlcyI6WyJhbm9ueW1vdXMiLCJ1c2VyIl0sInVzZXJuYW1lIjoiQW5kcmV5IFRoZSBNZXNzZW5nZXIiLCJpZCI6Ik5nS3lZLVhfNiIsImV4cGlyZXNPbiI6IjIwMTktMDctMTJUMTA6MDE6MjYuMjkwWiJ9.5wbsiswD_MEANxTRzODEqngTgfxcw9a52gKQ1byvuVM" >  qpc6e2NOY9s
2019/07/05 10:22:51 grpc in: get:<id:"mmwcff" topic:"me" query:<what:"sub desc" > >  zAGGeOGGco0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcdd9b2]

goroutine 361307 [running]:
main.replyOfflineTopicGetSub(0xc000332360, 0xc00042e2f0, 0xe, 0xc00011e640)
	/Users/gene/go/src/github.com/tinode/chat/server/hub.go:1132 +0x92
created by main.(*Hub).run
	/Users/gene/go/src/github.com/tinode/chat/server/hub.go:204 +0x6c3
```

Image tinode/tinode-rethinkdb:0.15.14

update: v0.15.15-rc2 has same behaviour

**Comment by or-else** [comment]
Yes, it's bug. Thank you for the report.

**Comment by or-else** [comment]
The fix has been released a while ago. Could you please confirm that it's fixed.

**Comment by afoninsky** [comment]
Sure, thank you
