### ISSUE TITLE
panic on devel branch with grpc instead of other adapters

### ISSUE THREAD

**Issue by AVVS** [tinode/chat#513]
on devel branch using grpc adapter. with json works fine - probably should add some tests cases :)

panic: interface conversion: interface {} is *pbx.ServerMsg, not []uint8

```
goroutine 56 [running]:
main.(*Session).queueOut(0xc0000cf760, 0xc000256120, 0x0)
	/home/runner/sl-tinode/server/session.go:263 +0x38b
main.(*Session).hello(0xc0000cf760, 0xc000259740)
	/home/runner/sl-tinode/server/session.go:682 +0x2c5
main.(*Session).dispatch(0xc0000cf760, 0xc000259740)
	/home/runner/sl-tinode/server/session.go:450 +0x41f
main.(*grpcNodeServer).MessageLoop(0x1c77598, 0x14dc980, 0xc000347a80, 0x0, 0x0)
	/home/runner/sl-tinode/server/hdl_grpc.go:63 +0x3bd
github.com/tinode/chat/pbx._Node_MessageLoop_Handler(0xf27ce0, 0x1c77598, 0x14d87e0, 0xc000b60780, 0x1c77598, 0xc000108800)
	/home/runner/sl-tinode/pbx/model.pb.go:3655 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00017a000, 0x14dde80, 0xc000226d80, 0xc000108800, 0xc000aee450, 0x1c34c40, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1329 +0xcdd
google.golang.org/grpc.(*Server).handleStream(0xc00017a000, 0x14dde80, 0xc000226d80, 0xc000108800, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1409 +0xc62
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000202820, 0xc00017a000, 0x14dde80, 0xc000226d80, 0xc000108800)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```

**Comment by or-else** [comment]
Thanks, I can reproduce.

You are welcome to send a pull request with test cases.

**Comment by or-else** [comment]
@aforge The crash is due to this conversion:
https://github.com/tinode/chat/blob/devel/server/session.go#L263
```go
statsAddHistSample("OutgoingMessageSize", float64(len(data.([]byte))))
```

It assumes that `data` is a `[]byte`, which is correct only in the case of a websocket connection:
https://github.com/tinode/chat/blob/devel/server/session.go#L1088

One way to solve it would be to make `serialize` return packet size as the second parameter. Intra-cluster messages can be counted as 0 size otherwise they would be counted at each node.

**Comment by aforge** [comment]
Ah, crap. Sorry about it. Will take care of it in a couple hours.

**Comment by aforge** [comment]
This should take care of it: https://github.com/tinode/chat/commit/cb6a176953dae728b1d6d2b2cd14c7e00b761d7b.
@AVVS let me know if you see other problems.
