### ISSUE TITLE
panic: runtime error: index out of range [12] with length 12

### ISSUE THREAD

**Issue by hhy5861** [tinode/chat#553]
version: v0.16.8-rc1

![image](https://user-images.githubusercontent.com/8274977/95166043-bde5fd80-07df-11eb-9fb9-aaa4b4525729.png)

```
panic: runtime error: index out of range [12] with length 12

goroutine 11923 [running]:
main.(*Topic).remProxiedSession(0xc000766d00, 0xc00088c780, 0xc00088c780)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3231 +0x30f
main.(*Topic).remSession(0xc000766d00, 0xc00088c780, 0x0, 0xc000201bc0, 0xc000661a78)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:3293 +0x3c6
main.(*Topic).handleLeaveRequest(0xc000766d00, 0xc0000a5f40, 0xc000354cd0)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:572 +0xd9
main.(*Topic).runLocal(0xc000766d00, 0xc0000a5f40)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:325 +0x14ce
main.(*Topic).run(0xc000766d00, 0xc0000a5f40)
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/topic.go:205 +0x58
created by main.topicInit
	/Users/mike/golang/poizon/duinfr/dewu-chat/server/init_topic.go:129 +0xdb4
```

**Comment by or-else** [comment]
@aforge Could you please take a look?

**Comment by aforge** [comment]
Sorry about this.
https://github.com/tinode/chat/commit/5742fa5c0806c16d501d0e96b534ffcfae71b547 should take care of it.
