### ISSUE TITLE
Connection failed (503),createAccount failed!

### ISSUE THREAD

**Issue by leapit** [tinode/chat#618]
### createAccount failed!
When use `tinode-sdk` as node js,at server side,
```
const Tinode = require('tinode-sdk')
const API_KEY = 'xxxxxxxxxxxxxxxxx'
const APP_NAME = 'Tinode-IM'
const HOST = 'localhost:6060'

Tinode.setNetworkProviders(require('ws'), require('xmlhttprequest'))
module.exports.NewClient = function() {
  const client = new Tinode(APP_NAME, HOST, API_KEY, 'ws', false, 'web')
  // client.enableLogging(true)
  client.onDisconnect = function(err) {
    console.log('Disconnect')
  }
  return client
}
```
and run a express router like this
```
exports.test = async function(req, res, next) {
  const { username, password, nickame, avatar, email } = { 'username': 'test', 'password': 'test123', 'nickame': 'Test Tinode', 'avatar': 'http://localhost:6060/img/logo32x32.png' }
  try {
    var tinode = require('./lib/tinode')
    const img2Base64 = require('./lib/img2Base64')
    var tinodeClient = tinode.NewClient()
    const payload = {
      username: username,
      password: password,
      displayName: nickame,
      avatar: avatar || '',
      email: email
    }
    const secret = btoa(payload.username + ':' + payload.password)
    const avatarData = await img2Base64(payload.avatar)
    const accParams = {
      public: {
        fn: payload.displayName,
        photo: {
          data: avatarData,
          type: 'png'
        }
      },
      tags: [payload.email, payload.username]
    }
    await tinodeClient.connect()
    const result = await tinodeClient.createAccount('basic', secret, false, accParams) //---->will got error
    console.log('---------------error---------------')
    console.log(result)
    if (result.code === 201) {
      console.log('error!', result)
    }
  } catch (err) {
    return utilities.output(200, 0, err.message, {})(req, res, next)
  }
}
```

`const result = await tinodeClient.createAccount('basic', secret, false, accParams) ` line will got error
```
Connection failed (503)
```
But,if change this line code with`const result = await tinodeClient.login('basic', secret)`,a login api call,it works,no 503 error,So I think createAccount problem should be a bug.

#### Server-side
  * platform (Mac)
  * version of Tinode server: `0.16.0`
  * database backend:`rethinkdb`
  * standalone

**Comment by or-else** [comment]
Please show client-size and server-side logs.

**Comment by leapit** [comment]
Hi, @or-else ,here is the full log from node server
```
Disconnect
Error: Connection failed (503)
    at WebSocket.h.onclose (/Users/tam/Work/chat-sdk/node_modules/tinode-sdk/umd/tinode.prod.js:1:14428)
    at WebSocket.onClose (/Users/tam/Work/chat-sdk/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/Users/tam/Work/chat-sdk/node_modules/ws/lib/websocket.js:198:10)
    at Socket.socketOnClose (/Users/tam/Work/chat-sdk/node_modules/ws/lib/websocket.js:886:15)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
GET /api/v1/sign/test 304 70.022 ms - -
```
It seems when call this createAccount api,the `Disconnect` happened.

**Comment by vkiller** [comment]
Found the same issue as your steps,it seems the tinode server reject the create account api request from another domain

**Comment by or-else** [comment]
I'm not sure what kind of API you are using but `GET /api/v1/sign/test` is not Tinode.

**Comment by or-else** [comment]
Can you reproduce the problem using the official web client?

**Comment by leapit** [comment]
It happened with js sdk(use node js),not web client,and there is no node server official demo.
the `GET /api/v1/sign/test` is a express node project,which call the `Tinode js sdk`,got error,the call function is in `test` function above

**Comment by or-else** [comment]
> It happened with js sdk(use node js),not web client,and there is no node server official demo.

You are welcome to create one.

Your `GET /api/v1/sign/test` returns `304` while the SDK expects `101`.

**Comment by vkiller** [comment]
@leapit @or-else Got the reason, `email` is undefined, `tags: [payload.email, payload.username]` has a undefined element,so got 503, I reproduce the problem below, run and test it http://localhost:3000/test 

```
var http = require('http')
http.createServer(function(req, res) {
  res.writeHead(200, { 'Content-Type': 'text/html' })
  var url = req.url
  if (url === '/test') {
    const Tinode = require('tinode-sdk')
    const API_KEY = 'your api key'
    const APP_NAME = 'Tinode-IM'
    const HOST = 'localhost:6060'
    Tinode.setNetworkProviders(require('ws'), require('xmlhttprequest'))
    const client = new Tinode(APP_NAME, HOST, API_KEY, 'ws', false, 'web')
    const payload = {
      username: 'myname3',
      password: 'mypassword',
      displayName: 'nickame'
    }
    const secret = btoa(payload.username + ':' + payload.password)
    const accParams = {
      public: {
        fn: payload.displayName
      },
      tags: [undefined, 'myname'] // here got error
    }

    client.connect().then(() => {
      return client.createAccount('basic', secret, false, accParams)
    }).then((ctrl) => {
      console.log(ctrl)
    }).catch((err) => {
      console.log(err)
    })
    // end
    res.end()
  } else {
    res.write('<h1>Test /test <h1>')
    res.end()
  }
}).listen(3000, function() {
  console.log('server start at port 3000') // the server object listens on port 3000
})

```
Just keep `tags: [undefined, 'myname']` a normal array,e.g. `tags: ['yourname@yourdomain', 'myname']`,that works!

**Comment by leapit** [comment]
@leapit @or-else Thanks for it,my mistake,close it.
