### ISSUE TITLE
GRPC: Tinode crashes with empty set_query:<>request

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/chat#624]
I was experimenting trying to understand why `get` sent together with  `sub` request does not return any data, and accidentally found the following:

If I send `set_query` with no data, Tinode crashes:

```
I2021/03/11 12:18:31 grpc in: hi:<id:"327800" user_agent:"php/grpc" ver:"1" lang:"es-ES" >  fc1PQm0NU7s
I2021/03/11 12:18:31 grpc in: login:<id:"148308" scheme:"token" secret:"\266\323\3202\336P\365\254\241\010K`\036\000\001\000\001\000Q\023\323<\230'\340\326k\326\316T6e\037x\312=|SJM\241\210\205\310\030!\017Z:\342" > auth_level:ROOT  fc1PQm0NU7s
I2021/03/11 12:18:31 grpc in: sub:<id:"969819" topic:"me" set_query:<> get_query:<what:"sub desc data del cred" > > on_behalf_of:"usrHGshCFWe5aI" auth_level:ROOT  fc1PQm0NU7s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc5bd3]

goroutine 407 [running]:
main.pbSetQueryDeserialize(0xc0006c42d0, 0xc000d06330)
        /Users/gene/go/src/github.com/tinode/chat/server/pbconverter.go:628 +0x153
main.pbCliDeserialize(0xc00007aaa0, 0x19)
        /Users/gene/go/src/github.com/tinode/chat/server/pbconverter.go:350 +0xf1b
main.(*grpcNodeServer).MessageLoop(0x1991d00, 0x137e7c0, 0xc000ade1f0, 0x0, 0x0)
        /Users/gene/go/src/github.com/tinode/chat/server/hdl_grpc.go:62 +0x3e5
github.com/tinode/chat/pbx._Node_MessageLoop_Handler(0xf16d40, 0x1991d00, 0x137b2e0, 0xc000da4fc0, 0x1991d00, 0xc00015c100)
        /Users/gene/go/src/github.com/tinode/chat/pbx/model.pb.go:3663 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000102ea0, 0x137f720, 0xc000642f00, 0xc00015c100, 0xc000edfc20, 0x1949320, 0x0, 0x0, 0x0)
        /Users/gene/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1329 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000102ea0, 0x137f720, 0xc000642f00, 0xc00015c100, 0x0)
        /Users/gene/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1409 +0xc5c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000812770, 0xc000102ea0, 0x137f720, 0xc000642f00, 0xc00015c100)
        /Users/gene/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/gene/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa5
```

**Comment by or-else** [comment]
What's the server version?

**Comment by or-else** [comment]
Actually, scratch that. I see the bug. Thanks.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/chat/commit/1e9426f738eae928d2a71b8761ec502941fff03b
