### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by gabriel-vasile** [tinode/chat#708]
Dereference on function result: https://github.com/tinode/chat/blob/f7a42cd16d9893a842bcf88caea58e0cad6a9f98/server/pbconverter.go#L419

Function result is nil:
https://github.com/tinode/chat/blob/f7a42cd16d9893a842bcf88caea58e0cad6a9f98/server/pbconverter.go#L641-L644

Can't `pbSetQueryDeserialize` behave like [pbGetQueryDeserialize](https://github.com/tinode/chat/blob/f7a42cd16d9893a842bcf88caea58e0cad6a9f98/server/pbconverter.go#L552-L580)?

**Comment by or-else** [comment]
Can you show the panic stacktrace?

**Comment by gabriel-vasile** [comment]
```bash
tinode      | panic: runtime error: invalid memory address or nil pointer dereference
tinode      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11817f3]
tinode      | 
tinode      | goroutine 42 [running]:
tinode      | main.pbCliDeserialize(0xc000be0e60)
tinode      | 	/opt/tinode/server/pbconverter.go:419 +0x833
tinode      | main.pluginFireHose(0x0, 0xc000b64180)
tinode      | 	/opt/tinode/server/plugins.go:391 +0x409
tinode      | main.(*Session).dispatch(0xc0001c6420, 0xc000b64180)
tinode      | 	/opt/tinode/server/session.go:485 +0x4da
tinode      | main.(*Session).dispatchRaw(0xc0001c6420, {0xc000518c00, 0x30, 0x200})
tinode      | 	/opt/tinode/server/session.go:460 +0x3fa
tinode      | main.(*Session).readLoop(0xc0001c6420)
tinode      | 	/opt/tinode/server/hdl_websock.go:62 +0x18d
tinode      | created by main.serveWebSocket
tinode      | 	/opt/tinode/server/hdl_websock.go:205 +0x5f1
```

**Comment by or-else** [comment]
Thanks. Fixed in https://github.com/tinode/chat/commit/596f42df0c910eeb372abc29d07a1304542da1ec
