### ISSUE TITLE
The go server changes the time zone, and the react client reports an error

### ISSUE THREAD

**Issue by wk482482** [tinode/chat#759]
I am in china so 

Change time.Now().UTC().Round(time.Millisecond)  to  time.Now().Round(time.Millisecond)

and change dsn to  “root:123456@tcp(localhost)/tinode?parseTime=true&loc=Local“

But  the react js  reports an error :

TypeError: e.getFullYear is not a function
    at A (strformat.js:5:12)
    at j.render (received-marker.jsx:32:19)
    at Te (react-dom.production.min.js:119:308)
    at Ch (react-dom.production.min.js:119:105)
    at Pj (react-dom.production.min.js:233:139)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
    at gf (react-dom.production.min.js:162:109)
    at react-dom.production.min.js:73:230

**Comment by or-else** [comment]
Please use form for questions.
