### ISSUE TITLE
Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by HeroSony** [tinode/chat#763]
I've got this error after searching another user by email and select on that user then got `Cannot read properties of undefined (reading 'getUserMedia')`

### Subject of the issue
<img width="1783" alt="Screen Shot 2022-06-16 at 10 55 29 PM" src="https://user-images.githubusercontent.com/4160246/174114047-e3262bac-bdc5-406d-b240-cb43e51ea290.png">

#### Server-side
- [ x] Own setup:
  * platform: Linux
  * version of Tinode server: [v0.19.1](https://github.com/tinode/chat/tree/v0.19.1)
  * database backend: mysql
  * cluster or standalone: standalone

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Server-side log
```
I2022/06/16 15:53:22 Server status is available at '/debug/status'
I2022/06/16 15:53:22 Large media handling enabled fs
I2022/06/16 15:53:22 Listening for client HTTP connections on [:6060]
I2022/06/16 15:53:44 ws: session started TOklrNG56I8 117.20.113.135:9029 1
I2022/06/16 15:53:45 in: '{"hi":{"id":"118125","ver":"0.19.1","ua":"TinodeWeb/0.19.1 (Chrome/102.0; MacIntel); tinodejs/0.19.1","lang":"en-US","platf":"web"}}' sid='TOklrNG56I8' uid=''
I2022/06/16 15:53:45 in: '{"acc":{"id":"118126","user":"new","scheme":"basic","secret":"aGVyb3Nvbnk6MTIzNDVoZXJvdmlyYWs=","login":true,"desc":{"public":{"fn":"herosony"}},"cred":[{"meth":"email","val":"simvirak7@gmail.com"}]}}' sid='TOklrNG56I8' uid=''
I2022/06/16 15:53:56 in: '{"login":{"id":"118127","scheme":"token","secret":"y3gbtGkYYXMJx71iFAABAAAAl3PUaDU1ypp1ZmOAmjnoOcoHvjiTRT4TxQ97PJymJuQ=","cred":[{"meth":"email","resp":"419721"}]}}' sid='TOklrNG56I8' uid=''
I2022/06/16 15:53:56 in: '{"sub":{"id":"118128","topic":"me","get":{"what":"sub desc tags cred"}}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
I2022/06/16 15:54:18 ws: session started OczU8x_YR_s 117.20.113.135:10991 2
I2022/06/16 15:54:18 in: '{"hi":{"id":"80627","ver":"0.19.1","ua":"TinodeWeb/0.19.1 (Chrome/102.0; MacIntel); tinodejs/0.19.1","lang":"en-US","platf":"web"}}' sid='OczU8x_YR_s' uid=''
I2022/06/16 15:54:18 in: '{"acc":{"id":"80628","user":"new","scheme":"basic","secret":"dmlyYWs6MTIzNDVoZXJvdmlyYWs=","login":true,"desc":{"public":{"fn":"virak"}},"cred":[{"meth":"email","val":"simvirak.inoted@gmail.com"}]}}' sid='OczU8x_YR_s' uid=''
I2022/06/16 15:54:31 in: '{"login":{"id":"80629","scheme":"token","secret":"Mfa+AiGVM+Mrx71iFAABAAAArs7qTrIcaW761OAOc1zAP5hyg3jWi+9vjF+UpMxqu24=","cred":[{"meth":"email","resp":"770660"}]}}' sid='OczU8x_YR_s' uid=''
I2022/06/16 15:54:32 in: '{"sub":{"id":"80630","topic":"me","get":{"what":"sub desc tags cred"}}}' sid='OczU8x_YR_s' uid='Mfa-AiGVM-M'
I2022/06/16 15:54:36 in: '{"sub":{"id":"118129","topic":"fnd","get":{"what":"sub"}}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
I2022/06/16 15:54:44 in: '{"set":{"id":"118130","topic":"fnd","desc":{"public":"simvirak.inoted@gmail.com"}}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
I2022/06/16 15:54:44 in: '{"get":{"id":"118131","topic":"fnd","what":"sub"}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
I2022/06/16 15:54:45 in: '{"set":{"id":"118132","topic":"fnd","desc":{"public":"␡"}}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
I2022/06/16 15:54:46 in: '{"get":{"id":"118133","topic":"fnd","what":"sub"}}' sid='TOklrNG56I8' uid='y3gbtGkYYXM'
```

### Client-side log
Copy client-side log here (Android logcat, Javascript console, etc). You may also attach it to the issue as a file.

**Comment by or-else** [comment]
I cannot reproduce. Please reproduce the problem using index-dev.html instead of index.html and port the javascript console output here.

Are you using a computer with no microphone and no camera?

**Comment by HeroSony** [comment]
I install it on linux server and run ./tinode to serve on port 6060.
Then I navigate to that server using its ip address with that port on my
client machine both mac and windows it have mic and camera installed.

**Comment by or-else** [comment]
Please reproduce the problem using index-dev.html instead of index.html and post the javascript console output here.

**Comment by HeroSony** [comment]
> Please reproduce the problem using index-dev.html instead of index.html and post the javascript console output here.

Let me try.

> Did you decline microphone and video permissions in the browser?

It's not pop up anything to ask permission to decline or not.

**Comment by HeroSony** [comment]
I change to serve on index-dev.html and here is the console output:
```
[17:24:01.808] out: {"set":{"id":"92913","topic":"fnd","desc":{"public":"␡"}}} 
index.dev.js:14652 Uncaught TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at new SendMessage (index.dev.js:14652:48)
    at constructClassInstance (react-dom.development.js:12739:11)
    at updateClassComponent (react-dom.development.js:17455:7)
    at beginWork (react-dom.development.js:19103:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at beginWork$1 (react-dom.development.js:23994:9)
    at performUnitOfWork (react-dom.development.js:22809:14)
    at workLoopSync (react-dom.development.js:22737:7)
SendMessage @ index.dev.js:14652
constructClassInstance @ react-dom.development.js:12739
updateClassComponent @ react-dom.development.js:17455
beginWork @ react-dom.development.js:19103
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
beginWork$1 @ react-dom.development.js:23994
performUnitOfWork @ react-dom.development.js:22809
workLoopSync @ react-dom.development.js:22737
renderRootSync @ react-dom.development.js:22700
performSyncWorkOnRoot @ react-dom.development.js:22323
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
scheduleUpdateOnFiber @ react-dom.development.js:21923
enqueueSetState @ react-dom.development.js:12497
Component.setState @ react.development.js:390
handleHashRoute @ index.dev.js:7897
hashchange (async)
navigateTo @ index.dev.js:2995
handleTopicSelected @ index.dev.js:8367
(anonymous) @ index.dev.js:8725
callCallback @ react-dom.development.js:12348
commitUpdateQueue @ react-dom.development.js:12369
commitLifeCycles @ react-dom.development.js:20739
commitLayoutEffects @ react-dom.development.js:23456
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23181
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:22450
discreteUpdates @ react-dom.development.js:3753
dispatchDiscreteEvent @ react-dom.development.js:5919
react-dom.development.js:20115 The above error occurred in the <SendMessage> component:

    at SendMessage (http://43.198.19.22:6060/umd/index.dev.js:14647:5)
    at injectIntl(SendMessage)
    at div
    at MessagesView (http://43.198.19.22:6060/umd/index.dev.js:5437:5)
    at injectIntl(MessagesView)
    at div
    at TinodeWeb (http://43.198.19.22:6060/umd/index.dev.js:7527:5)
    at injectIntl(TinodeWeb)
    at IntlProvider3 (https://cdn.jsdelivr.net/npm/react-intl@5/react-intl.iife.js:4418:45)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20115
update.callback @ react-dom.development.js:20148
callCallback @ react-dom.development.js:12348
commitUpdateQueue @ react-dom.development.js:12369
commitLifeCycles @ react-dom.development.js:20766
commitLayoutEffects @ react-dom.development.js:23456
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23181
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
scheduleUpdateOnFiber @ react-dom.development.js:21923
enqueueSetState @ react-dom.development.js:12497
Component.setState @ react.development.js:390
handleHashRoute @ index.dev.js:7897
hashchange (async)
navigateTo @ index.dev.js:2995
handleTopicSelected @ index.dev.js:8367
(anonymous) @ index.dev.js:8725
callCallback @ react-dom.development.js:12348
commitUpdateQueue @ react-dom.development.js:12369
commitLifeCycles @ react-dom.development.js:20739
commitLayoutEffects @ react-dom.development.js:23456
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23181
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:22450
discreteUpdates @ react-dom.development.js:3753
dispatchDiscreteEvent @ react-dom.development.js:5919
react-dom.development.js:11370 Uncaught TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at new SendMessage (index.dev.js:14652:48)
    at constructClassInstance (react-dom.development.js:12739:11)
    at updateClassComponent (react-dom.development.js:17455:7)
    at beginWork (react-dom.development.js:19103:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at beginWork$1 (react-dom.development.js:23994:9)
    at performUnitOfWork (react-dom.development.js:22809:14)
    at workLoopSync (react-dom.development.js:22737:7)
SendMessage @ index.dev.js:14652
constructClassInstance @ react-dom.development.js:12739
updateClassComponent @ react-dom.development.js:17455
beginWork @ react-dom.development.js:19103
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
beginWork$1 @ react-dom.development.js:23994
performUnitOfWork @ react-dom.development.js:22809
workLoopSync @ react-dom.development.js:22737
renderRootSync @ react-dom.development.js:22700
performSyncWorkOnRoot @ react-dom.development.js:22323
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
scheduleUpdateOnFiber @ react-dom.development.js:21923
enqueueSetState @ react-dom.development.js:12497
Component.setState @ react.development.js:390
handleHashRoute @ index.dev.js:7897
hashchange (async)
navigateTo @ index.dev.js:2995
handleTopicSelected @ index.dev.js:8367
(anonymous) @ index.dev.js:8725
callCallback @ react-dom.development.js:12348
commitUpdateQueue @ react-dom.development.js:12369
commitLifeCycles @ react-dom.development.js:20739
commitLayoutEffects @ react-dom.development.js:23456
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23181
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:22450
discreteUpdates @ react-dom.development.js:3753
dispatchDiscreteEvent @ react-dom.development.js:5919
tinode.js:466 [17:24:01.826] in: {"ctrl":{"id":"92913","topic":"fnd","code":200,"text":"ok","ts":"2022-06-16T17:24:01.810Z"}} 
react-dom.development.js:61 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at TinodeWeb (http://43.198.19.22:6060/umd/index.dev.js:7527:5)
    at injectIntl(TinodeWeb)
    at IntlProvider3 (https://cdn.jsdelivr.net/npm/react-intl@5/react-intl.iife.js:4418:45)
printWarning @ react-dom.development.js:61
error @ react-dom.development.js:37
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23944
scheduleUpdateOnFiber @ react-dom.development.js:21870
enqueueSetState @ react-dom.development.js:12497
Component.setState @ react.development.js:390
resetContactList @ index.dev.js:8294
tnMeSubsUpdated @ index.dev.js:8241
_processMetaDesc @ topic.js:1518
(anonymous) @ topic.js:540
Promise.then (async)
setMeta @ topic.js:510
setMeta @ topic.js:2265
handleSearchContacts @ index.dev.js:8335
handleSearchContacts @ index.dev.js:6726
componentWillUnmount @ index.dev.js:14496
callComponentWillUnmountWithTimer @ react-dom.development.js:20443
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
safelyCallComponentWillUnmount @ react-dom.development.js:20450
commitUnmount @ react-dom.development.js:20981
commitNestedUnmounts @ react-dom.development.js:21034
unmountHostComponents @ react-dom.development.js:21320
commitDeletion @ react-dom.development.js:21377
commitMutationEffects @ react-dom.development.js:23437
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
scheduleUpdateOnFiber @ react-dom.development.js:21923
enqueueSetState @ react-dom.development.js:12497
Component.setState @ react.development.js:390
handleHashRoute @ index.dev.js:7883
hashchange (async)
navigateTo @ index.dev.js:2995
handleTopicSelected @ index.dev.js:8367
(anonymous) @ index.dev.js:8725
callCallback @ react-dom.development.js:12348
commitUpdateQueue @ react-dom.development.js:12369
commitLifeCycles @ react-dom.development.js:20739
commitLayoutEffects @ react-dom.development.js:23456
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
commitRootImpl @ react-dom.development.js:23181
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
commitRoot @ react-dom.development.js:23020
performSyncWorkOnRoot @ react-dom.development.js:22359
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:22450
discreteUpdates @ react-dom.development.js:3753
dispatchDiscreteEvent @ react-dom.development.js:5919
Show 12 more frames
tinode.js:466 [17:24:01.828] out: {"get":{"id":"92914","topic":"fnd","what":"sub"}} 
tinode.js:466 [17:24:01.831] in: {"ctrl":{"id":"92914","topic":"fnd","params":{"what":"sub"},"code":204,"text":"no content","ts":"2022-06-16T17:24:01.829Z"}} 
```
<img width="1783" alt="Screen Shot 2022-06-17 at 12 25 28 AM" src="https://user-images.githubusercontent.com/4160246/174130591-57b0b301-8230-432b-92d0-8414a464d32f.png">

**Comment by or-else** [comment]
Ok, you are using it over HTTP instead of HTTPS:
https://stackoverflow.com/a/56005337

**Comment by or-else** [comment]
I'll add a fix to avoid a crash but voice messages will not work if used over HTTP

**Comment by HeroSony** [comment]
@or-else Ahh, I see. thanks...

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/webapp/commit/8cd8ffb6596e5b2113c04ad6cf40479890450a05
